"use client";

import { useMemo, useState } from "react";
import rawData from "./data/lithium-production.json";

type Value = { period: string; raw: string; value: number | null; mom: number | null };
type Company = { name: string; values: Value[] };
type Category = { key: string; name: string; unit: string; color: string; companies: Company[]; totals: Value[] };
const data = rawData as { meta: { title: string; latestPeriod: string; source: string; disclaimer: string }; periods: string[]; categories: Category[] };
const periods = data.periods.slice(-12);
const T = { brand: "\u4e1c\u5434\u7535\u65b0", title: "\u9502\u7535\u4ea7\u4e1a\u94fe\u6392\u4ea7\u6570\u636e\u5e93", month: "\u6708\u4efd", segment: "\u73af\u8282", raw: "\u539f\u59cb\u6570\u636e", company: "\u4f01\u4e1a", search: "\u641c\u7d22\u4f01\u4e1a", clear: "\u6e05\u9664", trend: "\u603b\u91cf\u8d8b\u52bf", line: "\u4f01\u4e1a\u6a2a\u5411\u5bf9\u6bd4", vertical: "\u516c\u53f8\u7eb5\u5411\u6570\u636e", value: "\u4ea7\u91cf", mom: "\u73af\u6bd4", structure: "\u4f01\u4e1a\u7ed3\u6784", observe: "\u73af\u6bd4\u89c2\u5bdf" };
const periodLabel = (p: string) => `${p.slice(2, 4)}.${p.slice(5)}`;
const fmt = (v: number | null | undefined, digits = 1) => v == null || !Number.isFinite(v) ? "—" : v.toLocaleString("zh-CN", { maximumFractionDigits: digits, minimumFractionDigits: digits });
const signed = (v: number | null) => v == null || !Number.isFinite(v) ? "—" : `${v >= 0 ? "+" : ""}${(v * 100).toFixed(1)}%`;
const latestValue = (company: Company, period: string) => company.values.find((v) => v.period === period)?.value ?? null;

function linePoints(company: Company, max: number) {
  return periods.map((p, i) => { const value = latestValue(company, p) ?? 0; const x = 24 + (i * 592) / Math.max(periods.length - 1, 1); const y = 206 - (value / Math.max(max, 1)) * 170; return `${x.toFixed(1)},${y.toFixed(1)}`; }).join(" ");
}

export function LithiumDashboard() {
  const [categoryKey, setCategoryKey] = useState("battery");
  const [period, setPeriod] = useState(data.meta.latestPeriod);
  const [search, setSearch] = useState("");
  const [mode, setMode] = useState<"value" | "mom">("value");
  const [selectedCompanyName, setSelectedCompanyName] = useState("");
  const category = data.categories.find((c) => c.key === categoryKey) ?? data.categories[0];
  const selectedTotal = category.totals.find((v) => v.period === period) ?? category.totals.at(-1)!;
  const rows = useMemo(() => category.companies.filter((r) => !search || r.name.includes(search.trim())), [category, search]);
  const selectedCompany = category.companies.find((c) => c.name === selectedCompanyName) ?? rows[0] ?? category.companies[0];
  const recentTotals = category.totals.filter((v) => periods.includes(v.period));
  const maxTotal = Math.max(...recentTotals.map((v) => v.value ?? 0), 1);
  const companyMax = Math.max(...category.companies.flatMap((c) => c.values.filter((v) => periods.includes(v.period)).map((v) => v.value ?? 0)), 1);
  const selectedMax = Math.max(...selectedCompany.values.filter((v) => periods.includes(v.period)).map((v) => v.value ?? 0), 1);
  const allLatest = data.categories.map((c) => ({ ...c, latest: c.totals.find((v) => v.period === period) ?? c.totals.at(-1)! }));
  const composition = rows.map((r) => ({ name: r.name, value: latestValue(r, period) ?? 0 })).sort((a, b) => b.value - a.value);
  const colors = ["#70b0e0", "#fcb714", "#2878bd", "#0eb194", "#f15628", "#af916d"];
  const selectCompany = (name: string, nextPeriod?: string) => { setSelectedCompanyName(name); if (nextPeriod) setPeriod(nextPeriod); };

  return <main className="pbix-shell">
    <header className="pbix-header"><div><div className="pbix-brand">{T.brand}</div><h1>{T.title}</h1><small>Li-ion production planning · Power BI style workspace</small></div><div className="pbix-filters"><label>{T.month}<select value={period} onChange={(e) => setPeriod(e.target.value)}>{data.periods.map((p) => <option key={p}>{p}</option>)}</select></label><label>{T.segment}<select value={categoryKey} onChange={(e) => { setCategoryKey(e.target.value); setSelectedCompanyName(""); }}>{data.categories.map((c) => <option key={c.key} value={c.key}>{c.name}</option>)}</select></label></div></header>
    <section className="pbix-kpis">{allLatest.map((c) => <button className={`pbix-kpi ${c.key === categoryKey ? "selected" : ""}`} key={c.key} onClick={() => { setCategoryKey(c.key); setSelectedCompanyName(""); }}><span>{c.name}</span><strong>{fmt(c.latest.value)}</strong><small>{c.unit} · {T.mom} <b className={c.latest.mom != null && c.latest.mom < 0 ? "down" : "up"}>{signed(c.latest.mom)}</b></small></button>)}</section>
    <div className="pbix-body"><section className="pbix-left"><div className="pbix-panel raw-panel"><div className="pbix-panel-head"><div><b>{T.raw}</b><small>{category.name} · {T.company} {"\u6392\u4ea7\u660e\u7ec6"} · {period}</small></div><div className="pbix-tools"><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder={T.search} /><button onClick={() => setSearch("")}>{T.clear}</button></div></div><div className="pbix-table-wrap"><table className="pbix-table"><thead><tr><th>{T.company}</th>{periods.map((p) => <th key={p}>{periodLabel(p)}</th>)}</tr></thead><tbody>{rows.map((r) => <tr className={selectedCompany?.name === r.name ? "selected-row" : ""} key={r.name} onClick={() => selectCompany(r.name)}><th>{r.name}</th>{periods.map((p) => { const v = r.values.find((x) => x.period === p); return <td key={p} title={v?.raw} onClick={(e) => { e.stopPropagation(); selectCompany(r.name, p); }}>{mode === "value" ? (v?.raw || "—") : signed(v?.mom ?? null)}</td>; })}</tr>)}</tbody></table></div><div className="pbix-note">{`\u70b9\u51fb\u4f01\u4e1a\u884c\u67e5\u770b\u7eb5\u5411\u56fe\uff1b\u70b9\u51fb\u5355\u5143\u683c\u540c\u65f6\u5207\u6362\u6708\u4efd\u3002\u539f\u59cb\u6587\u672c\u4fdd\u7559\u94c1\u9502\u3001\u4e09\u5143\u3001\u6e7f\u6cd5\u3001\u5e72\u6cd5\u7b49\u62c6\u5206\u3002`}</div></div></section>
      <section className="pbix-right"><div className="pbix-panel trend-panel"><div className="pbix-panel-head"><div><b>{category.name}{T.trend}</b><small>{`\u603b\u91cf\u4e0e\u6708\u5ea6${T.mom}`}</small></div><div className="pbix-toggle"><button className={mode === "value" ? "active" : ""} onClick={() => setMode("value")}>{T.value}</button><button className={mode === "mom" ? "active" : ""} onClick={() => setMode("mom")}>{T.mom}</button></div></div><div className="pbix-chart"><div className="pbix-yaxis"><span>{fmt(maxTotal, 0)}</span><span>{fmt(maxTotal / 2, 0)}</span><span>0</span></div><div className="pbix-bars">{recentTotals.map((v) => { const height = mode === "value" ? ((v.value ?? 0) / maxTotal) * 100 : Math.min(Math.abs(v.mom ?? 0) * 260, 100); return <div className="pbix-bar-item" key={v.period}><span className={v.mom != null && v.mom < 0 ? "down" : "up"}>{mode === "value" ? fmt(v.value) : signed(v.mom)}</span><i className={v.mom != null && v.mom < 0 ? "negative" : ""} style={{ height: `${Math.max(height, 3)}%` }} /><small>{periodLabel(v.period)}</small></div>; })}</div></div></div>
        <div className="pbix-panel line-panel"><div className="pbix-panel-head"><div><b>{category.name}{T.line}</b><small>{`\u6bcf\u6761\u7ebf\u4ee3\u8868\u4e00\u5bb6\u4f01\u4e1a\uff0c\u70b9\u51fb\u5de6\u4fa7\u4f01\u4e1a\u884c\u53ef\u8054\u52a8`}</small></div></div><div className="pbix-line-chart"><svg viewBox="0 0 640 240" role="img" aria-label={`${category.name}${T.line}`}><line x1="24" y1="206" x2="616" y2="206" /><line x1="24" y1="121" x2="616" y2="121" /><line x1="24" y1="36" x2="616" y2="36" />{category.companies.map((c, i) => <polyline key={c.name} points={linePoints(c, companyMax)} fill="none" stroke={colors[i % colors.length]} strokeWidth={selectedCompany?.name === c.name ? 3.2 : 1.6} opacity={selectedCompany?.name === c.name ? 1 : .65} />)}</svg><div className="pbix-line-labels">{periods.map((p) => <span key={p}>{periodLabel(p)}</span>)}</div></div><div className="pbix-legend">{category.companies.map((c, i) => <button className={selectedCompany?.name === c.name ? "active" : ""} key={c.name} onClick={() => selectCompany(c.name)}><i style={{ background: colors[i % colors.length] }} />{c.name}</button>)}</div></div>
        <div className="pbix-panel company-panel"><div className="pbix-panel-head"><div><b>{selectedCompany?.name ?? "—"}{T.vertical}</b><small>{period} · {category.name} · {category.unit}</small></div><strong className={selectedCompany?.values.find((v) => v.period === period)?.mom != null && (selectedCompany?.values.find((v) => v.period === period)?.mom ?? 0) < 0 ? "down" : "up"}>{signed(selectedCompany?.values.find((v) => v.period === period)?.mom ?? null)}</strong></div><div className="company-bars">{selectedCompany?.values.filter((v) => periods.includes(v.period)).map((v) => <div className="company-bar" key={v.period}><span>{fmt(v.value)}</span><i style={{ height: `${Math.max(((v.value ?? 0) / selectedMax) * 100, 3)}%` }} /><small>{periodLabel(v.period)}</small></div>)}</div></div>
        <div className="pbix-dual"><div className="pbix-panel composition-panel"><div className="pbix-panel-head"><div><b>{T.structure}</b><small>{period} · {category.unit}</small></div></div><div className="donut-wrap"><div className="pbix-donut"><div><strong>{fmt(selectedTotal.value)}</strong><small>{category.unit}</small></div></div><div className="donut-rows">{composition.slice(0, 6).map((r, i) => <div key={r.name}><i style={{ background: colors[i] }} /><span>{r.name}</span><b>{fmt(r.value)}</b></div>)}</div></div></div><div className="pbix-panel ratio-panel"><div className="pbix-panel-head"><div><b>{T.observe}</b><small>{`\u6700\u65b0\u6708\u4efd ${period}`}</small></div></div><div className="ratio-value"><strong className={selectedTotal.mom != null && selectedTotal.mom < 0 ? "down" : "up"}>{signed(selectedTotal.mom)}</strong><span>{`\u8f83\u4e0a\u6708`}</span></div><div className="ratio-list">{allLatest.map((c) => <div key={c.key}><span>{c.name}</span><b className={c.latest.mom != null && c.latest.mom < 0 ? "down" : "up"}>{signed(c.latest.mom)}</b></div>)}</div></div></div></section></div>
    <footer className="pbix-footer"><span>{`\u6570\u636e\u6765\u6e90\uff1a${data.meta.source}`}</span><span>{`\u6587\u4ef6\u66f4\u65b0\uff1a2026-08-05`}</span><span>{data.meta.disclaimer}</span></footer>
  </main>;
}
